apiVersion: v1
kind: Namespace
metadata:
  name: url-shortener-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  namespace: url-shortener-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: url-shortener:local-3
          env:
            - name: REDIS_ADDR
              value: redis.url-shortener-ns.svc.cluster.local:6379
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
        # Define the Redis container
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  namespace: url-shortener-ns
spec:
  selector:
    app: url-shortener
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: url-shortener-ns
spec:
  selector:
    app: url-shortener
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: url-shortener-nodeport
  namespace: url-shortener-ns
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: url-shortener
